select * from emp;
select * from dept;
select * from salgrade;
create table emp(eno number(2),ename varchar(3),ejob varchar(7),esal number(7),deptno number(2),grade varchar(2));
insert into emp values(&eno,'&ename','&ejob',&esal,&deptno,'&grade');
create table dept(dno number(2),dname varchar(10),dloc varchar(10));
insert into dept values(&dno,'&dname','&dloc');
create table salgrade(grade varchar(1),lowsal number(7),highsal number(7));
insert into salgrade values('&grade',&lowsal,&highsal);
select unique dname from dept where dno in (select deptno from emp);
select ename from emp where esal> (select esal from emp where ename='bcd');
select ename from emp where ejob in (select ejob from emp where ename='def');
select ename,esal from emp where esal > (select esal from emp where deptno=30);  
select lowsal from salgrade where grade in (select grade from emp where ename='abc');
select dname from dept where dno in (select deptno from emp where esal in (select max(esal) from emp )); 
select avg(esal) from emp where deptno in (select deptno from dept where deptno=20);
select * from emp where deptno in (select deptno from dept where deptno=20) and esal>170000;
select * from emp where deptno in (select deptno from dept where deptno=20) order by ename asc;
select ename from emp where esal > (select (lowsal+highsal)/2 from salgrade where emp.grade=salgrade.grade); 
select dname from dept where dno = (select deptno from emp group by deptno having count(deptno) > (select count(deptno) from emp where deptno in (select dno from dept where dname='banking')));   