create table accnt(ano varchar(10),cname varchar(10),bno varchar(10),atype varchar(7),aopen date,cbal number(7));
insert into accnt values('ca1','john','b1','ca','04-feb-2016',10000);
insert into accnt values('ca3','greeshma','b2','ca','03-may-2014',20000);
insert into accnt values('sb4','liya','b3','sb','07-apr-2014',40000);
insert into accnt values('sb1','yadhu','b1','sb','08-dec-2016',20000);
insert into accnt values('sb2','rohit','b2','sb','07-nov-2016',10000);
insert into accnt values('ca2','rohit','b2','ca','03-oct-2013',20000);
insert into accnt values('sb3','linju','b3','sb','03-sep-2012',20000);
select * from acont;
select avg(cbal) from accnt;
select min(cbal) from accnt;
select count(*) from accnt;
select cname from accnt where cbal=(select max(cbal) from accnt);
select sum(cbal) from acnnt;
select bno,count(ano) from accnt group by bno;
select cname from accnt having count(atype)>1 group by cname;
select bno,avg(cbal) from accnt group by bno;
select bno,count(ano) from accnt  where aopen >'03-01-2015' group by bno having count(ano)>1 ;
select bno,count(ano) from accnt group by bno;
select bno,count(ano) from accnt group by bno order by bno;
