create table book(isbl number(4),title varchar(15),mrp number(7),pname varchar(10),author varchar(15));
insert into book values(978,'db',650,'pearson','navathe');
insert into book values(980,'os',625,'wiley','slbersohatz');
insert into book values(920,'java',649,'mcgrawhll','schildt');
insert into book values(989,'microprocessor',720,'mcgrawhll','gaonker');
insert into book values(970,'algorithm',995,'mit','coreman');
create table pub(pid number(4),pname varchar(15),pcity varchar(10),pstate varchar(10),pcountry varchar(10));
insert into pub values(101,'pearson','la','california','usa');
insert into pub values(102,'wiley','sheffied','london','uk');
insert into pub values(103,'mcgrawhll','nycity','ny','usa');
insert into pub values(104,'bavaria','bavaria','berin','germany');
select * from book;
select * from pub;
select title,mrp,pcity from book left outer join pub on book.pname=pub.pname;
select * from book left outer join pub on book.pname=pub.pname;
select pub.pname,book.* from book right outer join pub on book.pname=pub.pname;
select pname from book union select pname from pub;
select pname from book intersect select pname from pub; 
select pname from book minus select pname from pub; 
